version: 0.0

os: linux

files:
  - source: target/release/alexlillianwedding
    destination: /usr/local/bin
  - source: static
    destination: /var/www/weddingwebsite

hooks:
  ApplicationStart:
    - location: scripts/launch.sh