version: 0.2

phases:
  install:
    commands:
      - echo "Installing Rust Nightly Toolchain"
      - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

  pre_build:
    commands:
      - echo "Adding cargo bin directory to PATH"
      - export PATH=$PATH:$HOME/.cargo/bin

  build:
    commands:
      - echo "Building Release Target with Cargo"
      - cargo build --release

  post_build:
    commands:
      - echo "Completed Build"

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - static/*
    - target/release/*