[package]
name = "alexlillianwedding"
version = "0.1.0"
authors = ["Alex"]

[dependencies]
lazy_static = "1.4"
maud = { version = "0.25", features = ["rocket"] }
rocket = { version = "0.5.0-rc.3", features = ["json"] }