[package]
name = "alexlillianwedding"
version = "0.1.0"
authors = ["Alex"]

[dependencies]
maud = { git = "https://github.com/anxiousmodernman/maud.git", branch = "121_proc_macro", features = ["rocket"] }
rocket = "0.3"
rocket_codegen = "0.3"