[package]
name = "alexlillianwedding"
version = "0.1.0"
authors = ["Alex"]

[dependencies]
lazy_static = "1.4.0"
maud = { version = "0.26.0", features = ["rocket"] }
rocket = { version = "0.5.0", features = ["json"] }