[package]
name = "alexlillianwedding"
version = "0.1.0"
authors = ["Alex"]
edition = "2024"

[dependencies]
lazy_static = "1.5"
maud = { version = "0.27", features = ["rocket"] }
rocket = { version = "0.5.1", features = ["json"] }